USE ROLE ACCOUNTADMIN;

-- Database 
CREATE DATABASE IF NOT EXISTS IW_TPCH_BENCH;
USE DATABASE IW_TPCH_BENCH;

-- Schemas
CREATE SCHEMA IF NOT EXISTS TPCH_SF{{SCALE}};
CREATE SCHEMA IF NOT EXISTS TPCH_SF{{SCALE}}_IT;

-- Temporary load warehouse to drive the CTAS
CREATE OR REPLACE WAREHOUSE IW_TPCH_LOAD_WH
  WAREHOUSE_SIZE = '{{LOAD_WH_SIZE}}'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = FALSE;

-- Check warehouse details;
-- SHOW WAREHOUSES LIKE 'IW_TPCH_LOAD_WH';

-- Use "load" warehouse
USE WAREHOUSE IW_TPCH_LOAD_WH;

-- 3. Standard tables 
USE SCHEMA TPCH_SF{{SCALE}};

CREATE OR REPLACE TABLE LINEITEM
  CLUSTER BY (L_SHIPDATE, L_ORDERKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.LINEITEM;

CREATE OR REPLACE TABLE ORDERS
  CLUSTER BY (O_ORDERDATE, O_ORDERKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.ORDERS;

CREATE OR REPLACE TABLE CUSTOMER
  CLUSTER BY (C_MKTSEGMENT, C_NATIONKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.CUSTOMER;

CREATE OR REPLACE TABLE PART
  CLUSTER BY (P_BRAND, P_SIZE)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.PART;

CREATE OR REPLACE TABLE PARTSUPP
  CLUSTER BY (PS_PARTKEY, PS_SUPPKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.PARTSUPP;

CREATE OR REPLACE TABLE SUPPLIER
  CLUSTER BY (S_NATIONKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.SUPPLIER;

CREATE OR REPLACE TABLE NATION
  CLUSTER BY (N_NATIONKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.NATION;

CREATE OR REPLACE TABLE REGION
  CLUSTER BY (R_REGIONKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.REGION;

-- Check created tables;
-- SELECT * FROM INFORMATION_SCHEMA.TABLES 
-- WHERE TABLE_SCHEMA = 'TPCH_SF{{SCALE}}';

-- Interactive tables 
-- Clustering keys derived from query analysis (see README.md).
USE SCHEMA TPCH_SF{{SCALE}}_IT;

CREATE OR REPLACE INTERACTIVE TABLE LINEITEM
  CLUSTER BY (L_SHIPDATE, L_ORDERKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.LINEITEM;

CREATE OR REPLACE INTERACTIVE TABLE ORDERS
  CLUSTER BY (O_ORDERDATE, O_ORDERKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.ORDERS;

CREATE OR REPLACE INTERACTIVE TABLE CUSTOMER
  CLUSTER BY (C_MKTSEGMENT, C_NATIONKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.CUSTOMER;

CREATE OR REPLACE INTERACTIVE TABLE PART
  CLUSTER BY (P_BRAND, P_SIZE)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.PART;

CREATE OR REPLACE INTERACTIVE TABLE PARTSUPP
  CLUSTER BY (PS_PARTKEY, PS_SUPPKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.PARTSUPP;

CREATE OR REPLACE INTERACTIVE TABLE SUPPLIER
  CLUSTER BY (S_NATIONKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.SUPPLIER;

CREATE OR REPLACE INTERACTIVE TABLE NATION
  CLUSTER BY (N_NATIONKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.NATION;

CREATE OR REPLACE INTERACTIVE TABLE REGION
  CLUSTER BY (R_REGIONKEY)
  AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF{{SCALE}}.REGION;

-- Check created tables;
-- SELECT * FROM INFORMATION_SCHEMA.TABLES 
-- WHERE TABLE_SCHEMA = 'TPCH_SF{{SCALE}}_IT';

-- Create standard warehouse 
CREATE WAREHOUSE IF NOT EXISTS TPCH_BENCH_WH_{{SCALE}}
  WAREHOUSE_SIZE = '{{BENCH_WH_SIZE}}'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Create interactive warehouse 
CREATE OR REPLACE INTERACTIVE WAREHOUSE IW_TPCH_BENCH_WH_{{SCALE}}
  TABLES (
    IW_TPCH_BENCH.TPCH_SF{{SCALE}}_IT.LINEITEM,
    IW_TPCH_BENCH.TPCH_SF{{SCALE}}_IT.ORDERS,
    IW_TPCH_BENCH.TPCH_SF{{SCALE}}_IT.CUSTOMER,
    IW_TPCH_BENCH.TPCH_SF{{SCALE}}_IT.PART,
    IW_TPCH_BENCH.TPCH_SF{{SCALE}}_IT.PARTSUPP,
    IW_TPCH_BENCH.TPCH_SF{{SCALE}}_IT.SUPPLIER,
    IW_TPCH_BENCH.TPCH_SF{{SCALE}}_IT.NATION,
    IW_TPCH_BENCH.TPCH_SF{{SCALE}}_IT.REGION
  )
  WAREHOUSE_SIZE = '{{BENCH_WH_SIZE}}';
ALTER WAREHOUSE IW_TPCH_BENCH_WH_{{SCALE}} RESUME IF SUSPENDED;

-- Check warehouse details;
--SHOW WAREHOUSES LIKE 'IW_TPCH_BENCH_WH_{{SCALE}}';

-- Drop "load" warehouse
DROP WAREHOUSE IW_TPCH_LOAD_WH;
